version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" #local:container
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql #create the database upon first time container starts (/var/lib/mysql is checked to be empty)